### ISSUE TITLE
3.2.47 / 3.2.48 Boot gif and stock broken

### ISSUE THREAD

**Issue by swas** [GeekMagicClock/smalltv-pro#101]
Hello!

I updated from V3.2.40EN to 3.2.47 / 3.2.48

And I noticed this:

The boot logo (boot.gif) doesn't work, it shows a broken pixel rainbow
The gif is the XP boot logo from this repo:
![image](https://github.com/user-attachments/assets/15e2a846-37a3-4162-ba98-6005df95c485)

The stock option is displayed empty with no data
![image](https://github.com/user-attachments/assets/11df3337-b4d0-4706-beed-1f057024f8a2)

Thanks a lot!

**Comment by swas** [comment]
Any help?
Tanks!

**Comment by GeekMagicClock** [comment]
@swas  Thank you, updated in 3.3.50, with faster gif play speed.

**Comment by swas** [comment]
Solved! Thanks a lot!
