### ISSUE TITLE
R24 resistor value

### ISSUE THREAD

**Issue by Popastefanx** [GeekMagicClock/smalltv-pro#104]
Hi guys anyone knows the value of the R24 resistor on the small tv pro. As i managed to rip mine off the board when installing batteries.

**Comment by GeekMagicClock** [comment]
Hi, it's 12KΩ 0402 risister, important components, but it's on your own risk.

**Comment by Popastefanx** [comment]
Thank you for the response will try adding it i have them home

**Comment by Popastefanx** [comment]
All working now its battery powered
