### ISSUE TITLE
Not displayed symbol in city name

### ISSUE THREAD

**Issue by Oleg16RUS** [GeekMagicClock/smalltv-pro#15]
Hello!

The name of my city contains the symbol < ' > (apostrophe). After updating the firmware to 3.2.21, the city name has a rectangle instead of an apostrophe.

I attached to issue photo of Clock and name on openweathermap

Thank you!

![GMC_Kazan](https://github.com/GeekMagicClock/smalltvpro/assets/149327418/f8772956-4ec9-432b-a5ab-00883046a75f)
![OWM_Kazan](https://github.com/GeekMagicClock/smalltvpro/assets/149327418/c6da43c7-9153-4e09-a4e3-92be7bdee0cc)

**Comment by Oleg16RUS** [comment]
May be in weather settings add a text field for customers set city name? If it fill, then shows city name from it field, else city name shows from openweathermap.

**Comment by GeekMagicClock** [comment]
Thank you for your feedback, i'll add this to next fix.

**Comment by GeekMagicClock** [comment]
Fixed, please update to the latest.
