### ISSUE TITLE
Bitcoin: background color for the value

### ISSUE THREAD

**Issue by eribertomota** [GeekMagicClock/smalltv-pro#28]
Hi @GeekMagicClock 

Thanks for your nice work. IMHO, currently, the orange background for the BTC price makes this data a bit unreadable on distance. Could you add a color configuration for the price and for the background?

**Comment by eribertomota** [comment]
Complementing, I would like to use a font bold white without a background. What you think about to add the possibility (maybe a new window for this) to create a setting to remove the graph and to use a bigger font?

**Comment by GeekMagicClock** [comment]
Hi, thank you for the advice, it's good suggestion, I'll try to offer the background/font color modify option. 
When you mention about the graph, do you mean the candle chart? Replace the chart with more bigger font?

**Comment by eribertomota** [comment]
> Hi, thank you for the advice, it's good suggestion, I'll try to offer the background/font color modify option. 

Thanks!

> When you mention about the graph, do you mean the candle chart? Replace the chart with more bigger font?

Yes, but also making available the chart option. I am an Arduino programmer (newbie) and I made a ticker with a display 128px showing the currency name and price for 5 currencies in last year. However, I don't have a good box for this and your project is very nice. I would like to have bigger numbers in your display to see the results in distance. For this option, I suggest removing the cents and to use a bold font, something like the attached picture.


![bignum](https://github.com/GeekMagicClock/smalltvpro/assets/6435502/aad7a0c4-b00a-466e-9eeb-72a4e57ed8ef)

**Comment by eribertomota** [comment]
Hummm.... BTC will arrive over USD 100.000 in 2025, so is needed to add space for one more number in my last suggestion.


![bignum2](https://github.com/GeekMagicClock/smalltvpro/assets/6435502/61f08160-2b8d-402e-827b-2ecb23a21a6f)

**Comment by GeekMagicClock** [comment]
Wow, got it, I'll try, thank you for this!

**Comment by GeekMagicClock** [comment]
Hello, we had add some simple theme, please update to the latest.
