### ISSUE TITLE
TCP/IP port for monitor

### ISSUE THREAD

**Issue by Null-Omega** [GeekMagicClock/smalltv-pro#29]
Hi!

Could you add the possibility to change TCP/IP port for remote system monitoring, since port 80 is occupied on the system I use (web server).

**Comment by GeekMagicClock** [comment]
Hello, I checked the latest version, it's already supported, but no clear explanation, you could set like this IP:PORT to the IP input area.

**Comment by Null-Omega** [comment]
Thank you, my issue could be resolved. I have one more request: please add a host name field to the network settings so that multiple devices could be easily found and distinguished.
