### ISSUE TITLE
How do I update the firmware on my smalltvpro?

### ISSUE THREAD

**Issue by learts13** [GeekMagicClock/smalltv-pro#32]
Hello Everybody!!!

![Uploading WhatsApp Image 2024-01-12 at 18.57.35.jpeg…]()
I got one today but when I tried to upgrade through the page the device reports on the IP it says that its memory is full.

How do I update the firmware through Windows? Do you have a teaching video?

**Comment by GeekMagicClock** [comment]
Hi, I can't see your picture, can you send a google drive link.

**Comment by learts13** [comment]
This is what I got. I bought it from your store on AliExpress. However, the
seller sent the smalltv version and I paid for the small TV Pro. Can you
help me?

Atenciosamente,
Leandro

Em sex., 12 de jan. de 2024 22:53, GeekMagic ***@***.***>
escreveu:

**Comment by GeekMagicClock** [comment]
Sorry, just ask them to return and replace with a new one.

**Comment by learts13** [comment]
In addition.

Shipping from Brazil to Hong Kong is 4 times the value of the product.

Best regards
Leandro

Em sáb., 13 de jan. de 2024 22:52, GeekMagic ***@***.***>
escreveu:
