### ISSUE TITLE
weather update interval

### ISSUE THREAD

**Issue by yanghoonkim** [GeekMagicClock/smalltv-pro#34]
Even I set the right api key for the weather (free plan, 60 requests per hour), the update interval is getting back to 20 minutes. I am using the latest firmware.

**Comment by 19201003080114** [comment]
- Enter the new correct API key
- Hit Save
- Change update interval
- Hit Save
If you only change the interval without a new valid API key first, it will revert back to 20 minutes

**Comment by GeekMagicClock** [comment]
Hello, how did you find the real update interval is 20 minutes?

**Comment by GeekMagicClock** [comment]
Hello, please update to v3.2.35
