### ISSUE TITLE
Time format cannot be change

### ISSUE THREAD

**Issue by wei5252** [GeekMagicClock/smalltv-pro#41]
The time format 24 and 12 cannot be changing even I enable it. It stay on 24 format. 

The clock page, not the weather page. 

I try enable it , save and reboot, nothing.

**Comment by GeekMagicClock** [comment]
Hi, thank you, is it already the latest?

**Comment by TheoCouss** [comment]
Hi! I have the same issue on the latest firmware

**Comment by GNARKiST** [comment]
I also have this issue on the latest firmware.

**Comment by GeekMagicClock** [comment]
@TheoCouss @GNARKiST @wei5252  Thank you all, please try the firmware here. 
[FW_SmallTV-PRO_V3.2.34EN.zip](https://github.com/GeekMagicClock/smalltv-pro/files/15427384/FW_SmallTV-PRO_V3.2.34EN.zip)

**Comment by wei5252** [comment]
Hey, thanks for the update. It's work now. But it does not have the day and night display beside or AM PM.

But I'm ok with the version now, thanks
