### ISSUE TITLE
Last candle on multiple timeframes are incorrectly displayed after last firmware update PRO_V3.2.29EN 

### ISSUE THREAD

**Issue by DadRe-dmt** [GeekMagicClock/smalltv-pro#50]
I really love the new layout but it seems to cause some display issues.

The last candle is not being displayed properly on multiple timeframes.
29 candles being displayed, candle 30 is floating offscreen.
Occurs on multiple timeframes 

Another issue :

The vs BTC pairs are not being properly displayed anymore.
Eth and Etc for instance are being showed as ET. 
The vs USDT pairs are properly displayed.

Would be great if this can be fixed.

**Comment by GeekMagicClock** [comment]
Hello, thanks for report first, could you upload some pictures? And your settings on the web too.

The USDT is no displayed cause the little space in the title area, they are all USDT pair in the Bitcoin App, people can keep in mind.

**Comment by DadRe-dmt** [comment]
Hi there, you can see the problem on the following  pictures.

![1](https://github.com/GeekMagicClock/smalltv-pro/assets/75391786/6c82dc37-4a90-4649-95c4-1ae170ab613d)


![2](https://github.com/GeekMagicClock/smalltv-pro/assets/75391786/af89583b-b96c-4146-bda5-310bd2b51173)

Thanks for taking the time to look into this.

**Comment by GeekMagicClock** [comment]
OK, now I got it, I'll try to fix it, I thought it only support USDT pairs, I was wrong, thank you for the info.

**Comment by DadRe-dmt** [comment]
Wow quick fix! 

This problem has been resolved after upgrading to the latest firmware V3.2.30EN

Candles are now fully visible and 'vs btc pairs' are correctly displayed.

Awesome work sir, Thank you!

**Comment by DadRe-dmt** [comment]
Strange. Some candles are still floating offscreen.





![6](https://github.com/GeekMagicClock/smalltv-pro/assets/75391786/6850c383-436d-4a14-8622-4199ecb1051d)

**Comment by GeekMagicClock** [comment]
OK, I'll check it out.

**Comment by GeekMagicClock** [comment]
Hi, please check the version V3.2.31, and I have change the candle number from 30 to 24, if you set the interval to 1h, then the chart shows the last 24hour prices.

**Comment by donatellosantoro** [comment]
Hello there,
I'm using this issue to report an incorrect display of the update time, when it is set to 15m.
The string "15m" will be partially cropped, as shown in this picture.

![telegram-cloud-photo-size-4-5917775802546637152-y](https://github.com/GeekMagicClock/smalltv-pro/assets/8266752/24c40667-395d-4362-9fcb-296556331313)

In addition (but this is a bit less important) on some localizations (for instance in Italy) the coma is used as thousands separator, while the dot is used as decimal separator.
It would be super nice to let the user choose this separators.

Thanks again for the great work!

**Comment by donatellosantoro** [comment]
> Hello there, I'm using this issue to report an incorrect display of the update time, when it is set to 15m. The string "15m" will be partially cropped, as shown in this picture.
> 
> ![telegram-cloud-photo-size-4-5917775802546637152-y](https://private-user-images.githubusercontent.com/8266752/330543005-24c40667-395d-4362-9fcb-296556331313.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2ODY3OTAsIm5iZiI6MTcxNzY4NjQ5MCwicGF0aCI6Ii84MjY2NzUyLzMzMDU0MzAwNS0yNGM0MDY2Ny0zOTVkLTQzNjItOWZjYi0yOTY1NTYzMzEzMTMuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMTUwODEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzdjNjVjNjliNzFhNmYzYzliYjQ2NWJmMGNmYjdjNDBmYzIxZTk4NTgwZDUwMDFkMjRkNTVhMDBhNDNlZmE2NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8uv1lJUxsKYcNntS_cFsOhDuLEQBtcreqX7BrwQ1Rb0)
> 
> In addition (but this is a bit less important) on some localizations (for instance in Italy) the coma is used as thousands separator, while the dot is used as decimal separator. It would be super nice to let the user choose this separators.
> 
> Thanks again for the great work!

Actually this issue is still there in the last firmware (3.2.37)
