### ISSUE TITLE
Display of cryptos

### ISSUE THREAD

**Issue by mellopps** [GeekMagicClock/smalltv-pro#52]
Hello dear Geekmagic team,
a great product - I love it.

Is it possible to extend the interface to Binance or use another one? 
 Binance only shows the prices of the coins you can buy there.

For example, KASUSDT (Kaspa) is not displayed, although the price is displayed on the BINANCE-page (but not listed on Binance).

Another example: RIOUSDT (Rio)

Can this be changed?

Thank you and best regards,
Philipp (mellopps)

**Comment by GeekMagicClock** [comment]
Hi, thank you like it.
You can try set "kas-usd" to the Stock app, that supports crypto too, and seems available.
But the Bitcoin app gets data from binance, they just do not offer data of some coins.

I apperciated if you could write some 5 star reviews on the product page, that would help us a lot, thanks.

**Comment by mellopps** [comment]
Thank you. Where can i give the 5 stars?

**Comment by GeekMagicClock** [comment]
> Thank you. Where can i give the 5 stars?

The link where you buy it, thank you.
