### ISSUE TITLE
weather and time

### ISSUE THREAD

**Issue by ArchangelV** [GeekMagicClock/smalltv-pro#60]
Hello,
First off, I love this little device. Great job. Second, I am not in any manner a coder/programmer or the alike. I know enough to be dangerous so to speak. I updated the firmware all good there but my issue is that my time is 12 hours ahead and the weather will not change to  deg F or actually show it. 

I am located in EST and the city code is https://openweathermap.org/city/5125086

I hope I explained this correctly, again I appreciate this device and your guidance.

**Comment by GeekMagicClock** [comment]
Hello, thanks for the report, I have test your citycode, is the the city Long Beach in New York?  Now 8:30 am, seems correct here on my device.

**Comment by ArchangelV** [comment]
Yes correct city. It is showing it as pm on mine as well as time on clock.
After noon local time it will show it is tomorrow.  At least on the clock
app. Weather on mine is not showing data beyond time.

**Comment by GeekMagicClock** [comment]
OK, the time is automatically updated after the weather info is synced, but if failed to get weather, then the timezone is a default one, so the time is not correct. Let's focus on the weather info, have you changed the weather API key? Or if other apps work? Can the bitcoin or stock info updated?

**Comment by ArchangelV** [comment]
I appreciate you very much..


I didn't change the api data I only did the most recent firmware update.
 The crypto is working fine. Stocks Fine as well. Just the clock and
weather seem to be at issue.

**Comment by GeekMagicClock** [comment]
Can you show me your settings on the web about weather options ?

**Comment by ArchangelV** [comment]
[screen shot device 2.pdf](https://github.com/GeekMagicClock/smalltv-pro/files/15253229/screen.shot.device.2.pdf)
[screen shot device.pdf](https://github.com/GeekMagicClock/smalltv-pro/files/15253230/screen.shot.device.pdf)

the city code is https://openweathermap.org/city/5122397    
I tried a few local ones to see if it would pull.

**Comment by GeekMagicClock** [comment]
Hi, the code is 5122397, number only.

**Comment by ArchangelV** [comment]
works perfect now... thank you I appreciate your time and attention.
