### ISSUE TITLE
Issue in http protocol with "Monitor" function

### ISSUE THREAD

**Issue by MyrikLD** [GeekMagicClock/smalltv-pro#64]
Hello. I want to create Aida64 display server emulator for linux, but I ran into a problem that prevents me from doing this.
As I can see from wireshark, device sending wrong header:
```
GET /sse HTTP/1.1\r\nContent-Type=application/json;charset=utf-8\r\nHost: 192.168.1.17:8080\r\nUser-Agent=ESP32\r\nConnection: close\r\n\r\n
```
Please, could you replace `Host: ` with `Host=` to comply with the http protocol?

**Comment by MyrikLD** [comment]
It would also be nice to have at least some documentation of this functionality. I would also really like to be able to send an image to the device, or at least the ability to start a poll of the specified host, which will return the finished image. This could greatly expand the scope of application of the device.

**Comment by GeekMagicClock** [comment]
> Hello. I want to create Aida64 display server emulator for linux, but I ran into a problem that prevents me from doing this. As I can see from wireshark, device sending wrong header:
> 
> ```
> GET /sse HTTP/1.1\r\nContent-Type=application/json;charset=utf-8\r\nHost: 192.168.1.17:8080\r\nUser-Agent=ESP32\r\nConnection: close\r\n\r\n
> ```
> 
> Please, could you replace `Host: ` with `Host=` to comply with the http protocol?

Hi, the "Host:" is correct, like other parameters in the http request header.

**Comment by MyrikLD** [comment]
Please, check documentation about http headers: https://developer.mozilla.org/en-US/docs/Glossary/HTTP_header

**Comment by GeekMagicClock** [comment]
> Please, check documentation about http headers: https://developer.mozilla.org/en-US/docs/Glossary/HTTP_header Ah, sorry, `Host` and `Connection` is ok, problem in `User-Agent` and `Content-Type`

Ah, yeah, you are correct, will fix it in the next update, thank you~

**Comment by GeekMagicClock** [comment]
[firmware-v3.2.34.zip](https://github.com/GeekMagicClock/smalltv-pro/files/15415865/firmware-v3.2.34.zip)

Here's a quick fix for you in case you may need it in time.

**Comment by MyrikLD** [comment]
Oh, thanks a lot!

**Comment by MyrikLD** [comment]
@GeekMagicClock `Content-Type` header still broken, `User-Agent` - fixed

**Comment by GeekMagicClock** [comment]
@MyrikLD  OK, please check this one. 
[firmware1-v3.2.34.zip](https://github.com/GeekMagicClock/smalltv-pro/files/15426700/firmware1-v3.2.34.zip)

**Comment by MyrikLD** [comment]
Works now
