### ISSUE TITLE
Bug - V3.2.37EN - stock percentages are confusing

### ISSUE THREAD

**Issue by chmurray-cisco** [GeekMagicClock/smalltv-pro#69]
Version: V3.2.37EN

The percentage change of a stock is never correct.

Example:
On smalltv-pro ticker ^IXIC shows +5.2% when its up only 0.37%.
Same problem for other tickers and currencies I've checked.

**Comment by chmurray-cisco** [comment]
Update: ok the percentage displayed relates to the period of 24 x <whatever interval you have set>, e.g. 24 days by default since it defaults to 24 candles of a day each.  In other words, it is not the days change.  If you make the interval much smaller, e.g. 5 minutes, you get 24 candles x 5 mins range and the percentage adjusts.  I wish there was an option to show percentage change from the day's open instead.

**Comment by GeekMagicClock** [comment]
Hello, you mean you want to display today's price change from the open time?

**Comment by chmurray-cisco** [comment]
Yes, percentage up or down on the day. Having percentage over last 24 candles (of varying time) is of limited value.

**Comment by GeekMagicClock** [comment]
@chmurray-cisco  Hi, please try this version, stock percent shows the price change percent of today.
[FW_SmallTV-PRO_V3.2.40EN.zip](https://github.com/user-attachments/files/15831264/FW_SmallTV-PRO_V3.2.40EN.zip)

**Comment by chmurray-cisco** [comment]
Hi, I've just testing 3.2.40, I'm seeing all percentages incorrect.

Example:
^IXIC showing 0.0% but actually up 0.14% today
^GSPC showing 0.0% but actually up 0.17% today
![image](https://github.com/GeekMagicClock/smalltv-pro/assets/64013980/0959b442-0994-499b-a20a-1cc354536be8)

**Comment by GeekMagicClock** [comment]
> Hi, I've just testing 3.2.40, I'm seeing all percentages incorrect.
> 
> Example: ^IXIC showing 0.0% but actually up 0.14% today ^GSPC showing 0.0% but actually up 0.17% today ![image](https://private-user-images.githubusercontent.com/64013980/340357448-0959b442-0994-499b-a20a-1cc354536be8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwODk4MTcsIm5iZiI6MTcyMzA4OTUxNywicGF0aCI6Ii82NDAxMzk4MC8zNDAzNTc0NDgtMDk1OWI0NDItMDk5NC00OTliLWEyMGEtMWNjMzU0NTM2YmU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDAzNTgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmNzk3YjVkMDU1NzJlMmI4NjYwMTM5YWEwZDY2NDhjOWIwMmM4YzFiMDAwMWI0Y2IyMTJhMGJiOGVjMzhmMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yKUi5r7bu02FK4hG7k0Peqz5ksaoKn8_CnM8-1g632E)

Thank you, the percent has been rounded in last version, please check the new one here. 
[firmware-V3.3.44.zip](https://github.com/user-attachments/files/16538017/firmware-V3.3.44.zip)

**Comment by chmurray-cisco** [comment]
I see its rounding to one decimal place - since that is all we have on screen - which is OK.
