### ISSUE TITLE
More Crypto tokens/coins

### ISSUE THREAD

**Issue by dadanunu1** [GeekMagicClock/smalltv-pro#77]
Is there a way to get more coins to show up? the lower cap ones aren't available. Maybe you can get them from coingecko or coinmarketcap. Thanks

**Comment by GeekMagicClock** [comment]
@dadanunu1  Hello, which coin do you perfer but could not be tracked on the device now?

**Comment by dadanunu1** [comment]
For example KNS(kenshi), AVI(aviator), QAN([QANplatform)

**Comment by dadanunu1** [comment]
I didn't think to check the stock app. Thanks!.
There's another problem. For example, the price of KNS is 0.02435 and the display only shows 0.02

**Comment by dadanunu1** [comment]
can this thing be done, to show the correct price?

**Comment by GeekMagicClock** [comment]
> can this thing be done, to show the correct price?

Yes, should be, I'll check it.

**Comment by dadanunu1** [comment]
thanks!

**Comment by GeekMagicClock** [comment]
@dadanunu1 Hello, please check this, v3.3.42. 
[FW_SmallTV-PRO_V3.3.42EN.bin.zip](https://github.com/user-attachments/files/16158388/FW_SmallTV-PRO_V3.3.42EN.bin.zip)

**Comment by dadanunu1** [comment]
Now it's perfect. Thanks!
