### ISSUE TITLE
Stock Graphs Not Displaying

### ISSUE THREAD

**Issue by rebeltaz** [GeekMagicClock/smalltv-pro#83]
I am running the stock firmware (Model: GeekMagic SmallTV-PRO,Version: V3.2.28EN) and the stock graphs do not display. Or if they do, they only show once in awhile. I have three stock symbols loaded - SI=F, GC=F and BTC-USD - and the price and change work, the graphic just doesn't show up.

**Comment by GeekMagicClock** [comment]
Hello, can you try the v3.3.40 ?

**Comment by rebeltaz** [comment]
I will try that tomorrow and let you know. Thank you.

**Comment by rebeltaz** [comment]
OK... so I updated to the 3.2.40 and the graphs are working. Thanks.
