### ISSUE TITLE
Stock Menu - Candle data inconsistency

### ISSUE THREAD

**Issue by iminchan** [GeekMagicClock/smalltv-pro#88]
Today is August 7th, but the candles for Tesla (TSLA) displayed are from June 4th to July 9th (24 days). BTC-USD candles cover June 25th to July 18th, showing inconsistency between stocks.

The interval (K-Line) is set to '1 day', and the firmware version is 3.2.40EN. The 'Bitcoin' menu is working fine.

I really like the product. Thanks to all developers.

![20240807_153835](https://github.com/user-attachments/assets/c3b22ea6-52c9-4dfe-8b87-63a6620cb1ff)
![Screenshot_20240807_153759_TradingView](https://github.com/user-attachments/assets/49e66466-87e2-478f-8ab8-1a76ccb56180)

**Comment by GeekMagicClock** [comment]
@iminchan  Thank you, please try this new version. https://github.com/GeekMagicClock/smalltv-pro/issues/69#issuecomment-2274974886

**Comment by iminchan** [comment]
> @iminchan Thank you, please try this new version. [#69 (comment)](https://github.com/GeekMagicClock/smalltv-pro/issues/69#issuecomment-2274974886)

Using V3.3.44, the candles are now displayed correctly.

Thank you!!
