### ISSUE TITLE
Stability Issues

### ISSUE THREAD

**Issue by edualm** [GeekMagicClock/smalltv-pro#93]
Hello,

I just got a SmallTV Pro, and I am running [V3.3.45EN.bin](https://github.com/GeekMagicClock/smalltv-pro/blob/main/firmware/PRO_V3.3.45EN/FW_SmallTV-PRO_V3.3.45EN.bin), which I updated to upon getting the device.

I am having a lot of stability issues though:

- The device occasionally reboots on its own (even while doing nothing);
- The device fails to connect to Wi-Fi upon boot randomly. I even created a separate Wi-Fi network just for it, 2.4G only with no optimizations, same issue;
- The Web UI crashes randomly (stops responding to requests), requiring me to manually restart the device to get it working again.

Is there any way I can do to make this work better? I like the device, but these small issues together make it unusable...

Thanks!

**Comment by edualm** [comment]
I've downgraded to [V3.2.40EN](https://github.com/GeekMagicClock/smalltv-pro/blob/main/firmware/PRO_V3.2.40EN/FW_SmallTV-PRO_V3.2.40EN.bin) and the problems seem to be gone.

Are there known issues with the latest firmware?

**Comment by GeekMagicClock** [comment]
@edualm  Thank you, yes, I have received this report, and here the attachment v3.3.46 is a test version, that seems caused by time sync under some network.
[FW_SmallTV-PRO_V3.3.46EN.zip](https://github.com/user-attachments/files/16861915/FW_SmallTV-PRO_V3.3.46EN.zip)

**Comment by edualm** [comment]
I tried `3.3.47`, it seems to have done the trick. Thanks!
